BEGIN;

CREATE TABLE IF NOT EXISTS plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    upload_quota INTEGER NOT NULL CHECK (upload_quota > 0),
    storage_limit_mb INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO plans (code, name, price, upload_quota)
VALUES ('FREE', 'Free', 0, 1), ('PLAN_99', '$99 Plan', 99, 25), ('PLAN_250', '$250 Plan', 250, 250)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, upload_quota = EXCLUDED.upload_quota;

CREATE TABLE IF NOT EXISTS user_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(user_id),
    plan_id BIGINT NOT NULL REFERENCES plans(id),
    status TEXT NOT NULL DEFAULT 'active',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    payment_provider TEXT,
    payment_reference TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS uploads_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS upload_quota INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE users
SET uploads_used = GREATEST(COALESCE(uploads_used, 0), COALESCE(upload_count, 0)),
    upload_quota = COALESCE(NULLIF(upload_quota, 0), 1);

INSERT INTO user_subscriptions (user_id, plan_id, status)
SELECT u.user_id, p.id, 'active' FROM users u CROSS JOIN plans p
WHERE p.code = 'FREE'
  AND NOT EXISTS (SELECT 1 FROM user_subscriptions s WHERE s.user_id = u.user_id AND s.status = 'active');

CREATE UNIQUE INDEX IF NOT EXISTS user_documents_user_document_key ON user_documents (user_id, document_id);
CREATE INDEX IF NOT EXISTS user_subscriptions_active_user_idx ON user_subscriptions (user_id, status);

COMMIT;