BEGIN;

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cin TEXT NOT NULL,
    pan TEXT,
    company_name TEXT,
    normalized_company_name TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT companies_cin_key UNIQUE (cin)
);

CREATE INDEX companies_pan_idx
    ON companies (pan)
    WHERE pan IS NOT NULL;

CREATE INDEX companies_normalized_company_name_idx
    ON companies (normalized_company_name)
    WHERE normalized_company_name IS NOT NULL;

CREATE TABLE company_users (
    company_id BIGINT NOT NULL,
    user_id TEXT NOT NULL,
    access_role TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT company_users_pkey PRIMARY KEY (company_id, user_id),
    CONSTRAINT company_users_company_id_fkey
        FOREIGN KEY (company_id)
        REFERENCES companies(id),
    CONSTRAINT company_users_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT company_users_access_role_check
        CHECK (access_role IN ('OWNER', 'CONSUMER'))
);

CREATE INDEX company_users_company_id_idx
    ON company_users (company_id);

CREATE INDEX company_users_user_id_idx
    ON company_users (user_id);

ALTER TABLE documents
    ADD COLUMN company_id BIGINT NULL;

ALTER TABLE documents
    ADD CONSTRAINT documents_company_id_fkey
        FOREIGN KEY (company_id)
        REFERENCES companies(id);

CREATE INDEX documents_company_id_idx
    ON documents (company_id);

COMMIT;