CREATE TABLE IF NOT EXISTS public.company_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    constitution TEXT NOT NULL DEFAULT 'Proprietorship',
    kyc_type TEXT NOT NULL DEFAULT 'PAN' CHECK (kyc_type IN ('PAN', 'GST', 'CIN')),
    email TEXT,
    contact_number TEXT,
    state TEXT,
    city TEXT,
    business_type TEXT NOT NULL DEFAULT 'Trader',
    product_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT company_profiles_company_id_fkey
        FOREIGN KEY (company_id)
        REFERENCES public.companies(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS company_profiles_company_id_idx
    ON public.company_profiles (company_id);
