-- ============================================================
-- FINANCIAL ANALYZER - SUPABASE SCHEMA
-- Migrated from current Neon PostgreSQL schema
-- ============================================================

-- ------------------------------------------------------------
-- 1. USERS
-- ------------------------------------------------------------

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE,
    user_name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    upload_count INTEGER NOT NULL DEFAULT 0,
    uploads_used INTEGER NOT NULL DEFAULT 0,
    upload_quota INTEGER NOT NULL DEFAULT 1,
    upload_limit_mb INTEGER,
    storage_used_mb INTEGER NOT NULL DEFAULT 0,
    storage_limit_mb INTEGER,
    role TEXT NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ------------------------------------------------------------
-- 2. DOCUMENTS
-- ------------------------------------------------------------

CREATE TABLE public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_hash TEXT NOT NULL,
    document_version INTEGER NOT NULL DEFAULT 1,
    original_filename TEXT,
    reporting_unit TEXT,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    extraction_status TEXT DEFAULT 'completed',
    extraction_payload JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id TEXT,

    CONSTRAINT fk_documents_user_id
        FOREIGN KEY (user_id)
        REFERENCES public.users(user_id)
);


-- ------------------------------------------------------------
-- 3. DOCUMENT TABLES
-- ------------------------------------------------------------

CREATE TABLE public.document_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    section_name TEXT NOT NULL,
    table_name TEXT NOT NULL,
    table_index INTEGER NOT NULL DEFAULT 0,
    rows_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT document_tables_document_id_fkey
        FOREIGN KEY (document_id)
        REFERENCES public.documents(id)
);


-- ------------------------------------------------------------
-- 4. DOCUMENT ROWS
-- ------------------------------------------------------------

CREATE TABLE public.document_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    table_id BIGINT,
    row_index INTEGER NOT NULL DEFAULT 0,
    row_values JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT document_rows_document_id_fkey
        FOREIGN KEY (document_id)
        REFERENCES public.documents(id),

    CONSTRAINT document_rows_table_id_fkey
        FOREIGN KEY (table_id)
        REFERENCES public.document_tables(id)
);


-- ------------------------------------------------------------
-- 5. FINANCIAL METRICS
-- ------------------------------------------------------------

CREATE TABLE public.financial_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    section_name TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    label TEXT,

    -- Financial values
    current NUMERIC,
    previous NUMERIC,

    notes TEXT,
    source_type TEXT DEFAULT 'extraction',
    created_at TIMESTAMPTZ DEFAULT NOW(),

    table_type VARCHAR,
    page INTEGER,
    year INTEGER,
    canonical_metric VARCHAR,

    normalized_value NUMERIC,
    original_value VARCHAR,
    original_header VARCHAR,
    confidence NUMERIC,

    is_total_row BOOLEAN DEFAULT FALSE,
    is_subtotal_row BOOLEAN DEFAULT FALSE,
    is_header_row BOOLEAN DEFAULT FALSE,
    is_blank_row BOOLEAN DEFAULT FALSE,

    row_index INTEGER,
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    table_id BIGINT,
    unit VARCHAR,

    CONSTRAINT financial_metrics_document_id_fkey
        FOREIGN KEY (document_id)
        REFERENCES public.documents(id)
);


-- ------------------------------------------------------------
-- 6. CALCULATED METRICS
-- ------------------------------------------------------------

CREATE TABLE public.calculated_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    metric_name TEXT NOT NULL,
    formula TEXT,
    result NUMERIC,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT calculated_metrics_document_id_fkey
        FOREIGN KEY (document_id)
        REFERENCES public.documents(id)
);


-- ------------------------------------------------------------
-- 7. METRIC VARIANCE ALERTS
-- ------------------------------------------------------------

CREATE TABLE public.metric_variance_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    metric_key TEXT,
    section_name TEXT,

    previous_value NUMERIC,
    current_value NUMERIC,
    variance_percent NUMERIC,

    severity TEXT DEFAULT 'warning',
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT metric_variance_alerts_document_id_fkey
        FOREIGN KEY (document_id)
        REFERENCES public.documents(id)
);


-- ------------------------------------------------------------
-- 8. ROW CHANGE LOG
-- ------------------------------------------------------------

CREATE TABLE public.row_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    previous_document_id BIGINT,
    metric_key TEXT,
    section_name TEXT,

    previous_value NUMERIC,
    new_value NUMERIC,

    change_type TEXT DEFAULT 'updated',
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT row_change_log_document_id_fkey
        FOREIGN KEY (document_id)
        REFERENCES public.documents(id),

    CONSTRAINT row_change_log_previous_document_id_fkey
        FOREIGN KEY (previous_document_id)
        REFERENCES public.documents(id)
);


-- ------------------------------------------------------------
-- 9. USER DOCUMENTS
-- ------------------------------------------------------------

CREATE TABLE public.user_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    document_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT user_documents_document_id_fkey
        FOREIGN KEY (document_id)
        REFERENCES public.documents(id)
);

CREATE UNIQUE INDEX user_documents_user_document_key
    ON public.user_documents (user_id, document_id);

CREATE TABLE public.plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    upload_quota INTEGER NOT NULL CHECK (upload_quota > 0),
    storage_limit_mb INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.user_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES public.users(user_id),
    plan_id BIGINT NOT NULL REFERENCES public.plans(id),
    status TEXT NOT NULL DEFAULT 'active',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    payment_provider TEXT,
    payment_reference TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ------------------------------------------------------------
-- 10. USER STORAGE LOGS
-- ------------------------------------------------------------

CREATE TABLE public.user_storage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    file_hash TEXT,
    file_size_mb NUMERIC,
    action TEXT DEFAULT 'uploaded',
    extraction_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT user_storage_logs_extraction_id_fkey
        FOREIGN KEY (extraction_id)
        REFERENCES public.documents(id)
);


-- ------------------------------------------------------------
-- 11. AUDIT LOGS
-- ------------------------------------------------------------

CREATE TABLE public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT,
    changes JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT audit_logs_admin_id_fkey
        FOREIGN KEY (admin_id)
        REFERENCES public.users(user_id)
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_documents_user_id
    ON public.documents(user_id);

CREATE INDEX idx_document_tables_document_id
    ON public.document_tables(document_id);

CREATE INDEX idx_document_rows_document_id
    ON public.document_rows(document_id);

CREATE INDEX idx_document_rows_table_id
    ON public.document_rows(table_id);

CREATE INDEX idx_financial_metrics_document_id
    ON public.financial_metrics(document_id);

CREATE INDEX idx_calculated_metrics_document_id
    ON public.calculated_metrics(document_id);

CREATE INDEX idx_metric_variance_alerts_document_id
    ON public.metric_variance_alerts(document_id);

CREATE INDEX idx_row_change_log_document_id
    ON public.row_change_log(document_id);

CREATE INDEX idx_row_change_log_previous_document_id
    ON public.row_change_log(previous_document_id);

CREATE INDEX idx_user_documents_document_id
    ON public.user_documents(document_id);

CREATE INDEX idx_user_storage_logs_user_id
    ON public.user_storage_logs(user_id);

CREATE INDEX idx_user_storage_logs_extraction_id
    ON public.user_storage_logs(extraction_id);

CREATE INDEX idx_audit_logs_admin_id
    ON public.audit_logs(admin_id);